spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/llmall?characterEncoding=utf-8
    username: root
    password: root1234
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.lltech.llmall.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl